[build]  
  command = "cd client && yarn && cd ../types && yarn && cd ../client && yarn build"
  publish = "client/dist"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
